add the requirements to Readme.md
YuZhangYuanYYZ/purchasePhone pull request #1
Opened 2019-03-09 06:27 UTC by YuZhangYuanYYZ

2019-03-09 06:42 UTC, lanmengyujing commented
looks good to me

2019-03-09 06:42 UTC, lanmengyujing approved these changes

2019-03-09 10:41 UTC, lanmengyujing commented on purchasePhone.js
> +   function bankrupt(){
```suggestion
   function isBankrupt(thresholdSpending, totalSpendingMoney, bankMoney ){  
   return ((thresholdSpending-totalSpendingMoney)>0)&&((bankMoney-totalSpendingMoney)>0);
       
   }
```

2019-03-09 10:42 UTC, lanmengyujing commented on purchasePhone.js
> +    while (bankrupt()){
```suggestion
    while (!isbankrupt(thresholdSpending, totalSpendingMoney, bankMoney )){
       ....
    }
```

2019-03-09 10:44 UTC, lanmengyujing commented on purchasePhone.js
>  function totalSpending(){
```suggestion
function calculateSpending(n, accesorieyPrice, phonePrice  ){    
   .... 
    return total;
}  
```

2019-03-09 10:50 UTC, lanmengyujing commented on purchasePhone.js
>      moneyOfAcc = n*accesorieyPrice;
var moneyOfAcc = n*accesorieyPrice;

2019-03-09 10:51 UTC, lanmengyujing commented on purchasePhone.js
function caculateTax(totalPrice, taxRate) {
  return totalPrice * taxRate;
}

2019-03-09 12:09 UTC, lanmengyujing requested changes
see comments

2019-03-10 02:37 UTC, lanmengyujing commented on purchasePhone.js
> +    }
```suggestion
 function isBankrupt(thresholdSpending, totalSpendingMoney, bankMoney) {
    return ((thresholdSpending - totalSpendingMoney) > 0) && ((bankMoney - totalSpendingMoney) > 0);
}

```

2019-03-10 02:38 UTC, lanmengyujing commented on purchasePhone.js
> +        while (isBankrupt(phonePrice,accesorieyPrice,taxRate,phoneAmount,thresholdSpending,bankMoney,totalSpendingMoney )){
```suggestion
    while (!isBankrupt(threshold, total, bankMoney)) {

```

2019-03-10 12:24 UTC, lanmengyujing commented on purchasePhone.js
> +        allSpendingMoney: spendingMoney(phonePrice,accesorieyPrice,phoneAmount-1,taxRate),
why calculate again here？

2019-03-10 12:25 UTC, lanmengyujing commented on purchasePhone.js
> +        var phoneAmount = buyPhones(thresholdSpending,bankMoney).phoneAmount-1;
buyPhones(thresholdSpending,bankMoney) is duplicate in line 34 and 35

2019-03-10 12:25 UTC, lanmengyujing commented on purchasePhone.js
> +        console.log("the number of phone you have bought is:"+(phoneAmount)+","+ "the money you have spent(with tax) is:$"+allSpendingMoney);
print those information in another function instead of directly call `console.log`

2019-03-10 12:44 UTC, merged

2019-03-10 12:44 UTC, YuZhangYuanYYZ commented on purchasePhone.js
> +    while (bankrupt()){
have modified

2019-03-15 12:07 UTC, lanmengyujing commented on purchasePhone.js
> +        var phoneAmount = buyPhones(thresholdSpending,bankMoney).phoneAmount-1;
here

2019-03-15 12:07 UTC, lanmengyujing commented on purchasePhone.js
> +        allSpendingMoney: spendingMoney(phonePrice,accesorieyPrice,phoneAmount-1,taxRate),
and here

2019-03-15 12:07 UTC, lanmengyujing commented on purchasePhone.js
> +        var allSpendingMoney = buyPhones(thresholdSpending,bankMoney).allSpendingMoney;
here

2019-03-15 12:09 UTC, lanmengyujing commented on purchasePhone.js
> +        allSpendingMoney: spendingMoney(phonePrice,accesorieyPrice,phoneAmount-1,taxRate),
why calculate here again